services:
  db-test:
    image: mysql:8.0
    ports:
      - '3310:3306'
    volumes:
      - db_data_test:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auction_test
      MYSQL_USER: devusr
      MYSQL_PASSWORD: devpwd
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--silent']
      timeout: 30s
      interval: 30s
      retries: 5
      start_period: 30s

volumes:
  db_data_test:
